name: train-my-model

on: [push]

jobs:
  run:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: build
        shell: bash
        run: |
          sudo apt-get remove libboost-all-dev
          sudo add-apt-repository ppa:mhier/libboost-latest
          sudo apt-get update && sudo apt-get install -y swig libboost1.68 libboost1.68-dev
          mkdir build
          cd build && cmake .. && make

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "Release/*"
          token: ${{ secrets.GITHUB_TOKEN }}